In [2]:
import numpy as np

In [4]:
class HMM:

    def vtbAlg(self):
        
        seq=np.array(['G','G','C','A','C','T','G','A','A'])
        seqInt=self.convert_to_int(seq)
        states=['H','L']
        start_prob=np.array([-1,-1])
        num_of_states=np.array(start_prob.shape[0])
        
        #instantiating arrays required to calculate probabilities
        transitions=np.array([[-0.737, -1.322], [-1,-1]])
        obs_prob=np.array([[-1.737,-2.322,-2.322,-1.737],[-2.322,-1.737, -1.737,-2.322]])
        lenSeq=seqInt.shape[0]
        probability_mat=np.zeros((num_of_states,lenSeq))
        backtrack_mat=np.zeros((num_of_states, lenSeq-1))
        probability_mat[:, 0] =  start_prob + obs_prob[:, seqInt[0]]
        
        for i in range(1, lenSeq):
            for j in range(num_of_states):
                #adding since using log probabilities
                calcProb= transitions[:,j] + probability_mat[:,i-1]
                #calculate the missing values making use of Equation 1
                probability_mat[j,i] = np.max(calcProb) + obs_prob[j,seqInt[i]]
                #record which decision was taken in the max() calculation
                backtrack_mat[j, i-1] = np.argmax(calcProb)

        probable_path=np.zeros(lenSeq)
        probable_path[-1] = np.argmax(probability_mat[:, -1])
        
        for n in range(lenSeq-2, -1, -1):
            probable_path[n] = backtrack_mat[int( probable_path[n+1]), n]
            print(backtrack_mat)
        probability_mat = np.flip(probability_mat, 0)
        probable_path = self.convert_state_to_int(probable_path)
        backtrack_mat = self.convert_backtrack_to_int (backtrack_mat)
        print("Probability values:")
        print(probability_mat)
        print("Decisions:")
        print(backtrack_mat)
        print("Probable path:")
        print(probable_path)
                
    #used to convert observations into ints and returns the list of ints
    def convert_to_int(self, seq):
        newSeq=np.zeros((seq.shape[0]),dtype=int)
        for i in range (seq.shape[0]):
            if(seq[i] == 'G'):
                newSeq[i]=2
            elif(seq[i]=='A'):
                newSeq[i]=0
            elif(seq[i]=='C'):
                newSeq[i]=1
            elif(seq[i]=='T'):
                newSeq[i]=3
            else:
                 print("error")
        return(newSeq)
    
    #converts the states to ints and returns the list of ints
    def convert_state_to_int(self,state):
        newStates = np.zeros (state.shape[0],dtype=str)
        for i in range (state.shape[0]):
            if(state[i]==1):
                newStates[i]='H'
            elif (state[i]==0):
                newStates[i]='L'
        return newStates
    
    def convert_backtrack_to_int (self,state):
        newMat = np.zeros ((state.shape[0],state.shape[1]+1),dtype = str)
        newMat[0][0]='S'
        newMat[1][0]='S'
        for i in range (state.shape[0]):
            for j in range (1,state.shape[1]+1):
                if(state[i][j-1]==1):
                    newMat[i][j]='H'
                elif (state[i][j-1]==0):
                    newMat[i][j]='L'
        return newMat
                
hmm=HMM()
hmm.vtbAlg()

[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0.]]
[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0.]]
[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0.]]
[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0.]]
[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0.]]
[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0.]]
[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0.]]
[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0.]]
Probability values:
[[ -2.737  -5.474  -8.211 -11.533 -14.007 -17.329 -19.54  -22.862 -25.658]
 [ -3.322  -6.059  -8.796 -10.948 -14.007 -16.481 -19.54  -22.014 -24.488]]
Decisions:
[['S' 'H' 'H' 'H' 'L' 'L' 'L' 'L' 'L']
 ['S' 'H' 'H' 'H' 'L' 'H' 'L' 'H' 'L']]
Probable path:
['H' 'H' 'H' 'L' 'L' 'L' 'L' 'L' 'L']
